permalink: /:title/
url: http://jeizas.github.io
markdown: macdown
highlighter: rouge
#highlighter: pygments
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page:num"
name: jeizas
description: jeizas | Stop talking, start doing.
author: jeizas
email: jeizas1210@gmail.com
duoshuo: jeizas
weibo: 3903459146
hub: jeizas
safe: false
about: "弱菜一枚。"
gems: [jekyll-paginate]
